areyoufree:
    build: .
    container_name: areyoufree
    command: gunicorn --name areufree -b 0.0.0.0:1500 -w 2 wsgi:app
    ports:
        - "1500:1500"
    links:
        - redis

redis:
    image: redis
    command: redis-server --port 6380
    ports:
        - "6380:6380"
